### ISSUE TITLE
eMBMS Multicast

### ISSUE THREAD

**Issue by OmarEltobgy** [chunyeow/openairinterface5g#6]
Greetings, 

I would like to ask if eMBMS is implemented to get the multicast functionalities ?
eMBMS requires 3 new parts MCE (Multi-call/multicast Coordination Entity), MBMS Gateway(GW), and BM-SC. 

If not, when is it expected to be released. 

Best Regards,
Omar Eltobgy

**Comment by chunyeow** [comment]
"For eMBMS, it should be a bit simpler to get things running again, although we haven't tried in a while. Hopefully, one of our partners will intergrate the UE work that they did into the codebase which allows operation with commercial eNBs.  For the infrastructure end, we have no EPC support in openairCN for eMBMS unfortunately, somebody will have to develop that if they're interested. The RAN component is mostly done for the eNB, although we have never done any interoperability testing with commercial UEs."

Capture from reply of Raymond's answer on 22 August 2017.

I think that you need to try out your own and explore the core network to support this. Explore https://gitlab.eurecom.fr/oai/openairinterface5g/ and join the mailing list to get more info.

**Comment by OmarEltobgy** [comment]
So, Would you please tell me the steps to set up an embms test bed ? 
Or even the things that i should read or study because the documentation is huge and i just want to get things running and add/modify some parts without getting involved in all the details. 

For example, for the EPC support can i buy a commercial EPC and if so from where and for how much money ? 

Given i have the EPC code how to integrate it with other parts ? 

It would be awesome if you can help me. 

Thanks in Advance

**Comment by chunyeow** [comment]
On Aug 26, 2017 9:05 AM, "Omar Khaled Eltobgy" <notifications@github.com>
wrote:

So, Would you please tell me the steps to set up an embms test bed ?

I haven't tried this before can't comment much. Just shoot an email to the
open area mailing list. The community may help you.

Or even the things that i should read or study because the documentation is
huge and i just want to get things running and add/modify some parts
without getting involved in all the details.

For example, for the EPC support can i buy a commercial EPC and if so from
where and for how much money ?

You can buy software based EPC which is cheaper, such as Amarisoft

Given i have the EPC code how to integrate it with other parts ?

For openair-cn, you just get the code from gitlab

It would be awesome if you can help me.

Thanks in Advance

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/chunyeow/openairinterface5g/issues/6#issuecomment-325060585>,
or mute the thread
